"""
Script to generate and visualize best paths between two random nodes in a road network using Folium.
Requires the edges and nodes GeoJSON files to be generated by the 0_cartography script.
"""

import argparse
from pathlib import Path

import folium
import geopandas as gpd
from dsf import logging
from dsf.mobility import RoadNetwork

INPUT_DIR = Path("../0_cartography/output")
OUTPUT_DIR = Path("output")

COLORS = ["blue", "red", "green", "purple", "orange", "darkred", "cadetblue"]


def main(weight: str = "traveltime", threshold: float | None = None, seed: int = 69):
    gdf_edges = gpd.read_file(INPUT_DIR / "edges.geojson").set_geometry("geometry")
    gdf_nodes = gpd.read_file(INPUT_DIR / "nodes.geojson").set_geometry("geometry")

    # Extract two random nodes from the nodes GeoDataFrame
    random_nodes = gdf_nodes.sample(n=2, random_state=seed)
    INIT_NODE = random_nodes.iloc[0]["id"]
    DEST_NODE = random_nodes.iloc[1]["id"]

    logging.info(f"Selected initial node: {INIT_NODE}, destination node: {DEST_NODE}")

    road_network = RoadNetwork()
    road_network.importEdges((INPUT_DIR / "edges.geojson").as_posix())
    if threshold is not None:
        road_network.setEdgeWeight(weight, threshold=threshold)
    else:
        road_network.setEdgeWeight(weight)

    path_collection = road_network.allPathsTo(DEST_NODE)
    all_paths = path_collection.explode(INIT_NODE, DEST_NODE)

    logging.info(
        f"Found {len(all_paths)} equivalent path(s) from node {INIT_NODE} to node {DEST_NODE}."
    )

    m = folium.Map(
        location=[
            gdf_edges.iloc[0]["geometry"].centroid.y,
            gdf_edges.iloc[0]["geometry"].centroid.x,
        ],
        zoom_start=13,
    )

    for path_idx, best_path in enumerate(all_paths):
        # Cycle through colors if there are more paths than colors
        path_color = COLORS[path_idx % len(COLORS)]

        for i in range(len(best_path) - 1):
            # Filter for the specific edge
            edge = gdf_edges[
                (gdf_edges["source"] == best_path[i])
                & (gdf_edges["target"] == best_path[i + 1])
            ]

            # Guard clause: Skip if the edge doesn't exist in the GeoDataFrame
            if edge.empty:
                raise ValueError(
                    f"Edge from {best_path[i]} to {best_path[i + 1]} not found in edges GeoDataFrame."
                )

            coords = edge.iloc[0]["geometry"].coords[:]
            # Swap coordinates to (lat, lon) format
            coords = [(y, x) for x, y in coords]

            # Add PolyLine with a unique popup showing which path it belongs to
            folium.PolyLine(
                coords,
                color=path_color,
                weight=5
                - (path_idx * 0.5),  # Slightly thinner lines for overlapping paths
                opacity=0.8,
                popup=f"Path {path_idx + 1}, Edge {i}",
            ).add_to(m)

    m.save(OUTPUT_DIR / "best_paths.html")
    logging.info(f"Successfully mapped {len(all_paths)} equivalent path(s)!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate best paths for a given city."
    )
    parser.add_argument(
        "--weight",
        help="The weight to use for the edges (default: traveltime).",
        type=str,
        default="traveltime",
    )
    parser.add_argument(
        "--threshold",
        help="The threshold to use for the edges (default: None).",
        type=float,
        default=None,
    )
    parser.add_argument(
        "--seed",
        help="The random seed to use (default: 69).",
        type=int,
        default=69,
    )
    args = parser.parse_args()
    OUTPUT_DIR.mkdir(exist_ok=True)
    main(args.weight, args.threshold, args.seed)
