"""
Script to generate and visualize forbidden turns in a road network using Folium.
Requires the edges GeoJSON file to be generated by the 0_cartography script.
"""

from pathlib import Path

import folium
from folium.plugins import AntPath
import geopandas as gpd
import numpy as np
from dsf import logging

INPUT_DIR = Path("../0_cartography/output")
OUTPUT_DIR = Path("output")


def main():
    if not (INPUT_DIR / "edges.geojson").exists():
        logging.error(
            f"Edges GeoJSON file not found in {INPUT_DIR}. Please run the 0_cartography script first."
        )
        return
    edges = gpd.read_file(INPUT_DIR / "edges.geojson")
    edges.set_index("id", inplace=True)

    # Initialize map centered on Bologna
    m = folium.Map(
        location=[
            edges["geometry"].centroid.y.mean(),
            edges["geometry"].centroid.x.mean(),
        ],
        zoom_start=14,
    )

    # 1. Base Layer: Plot all roads in blue first
    for index, row in edges.iterrows():
        base_coords = [(lat, lon) for lon, lat in row["geometry"].coords]
        folium.PolyLine(
            locations=base_coords,
            color="blue",
            weight=2,
            opacity=0.6,
            tooltip=f"Road: {index}",
        ).add_to(m)

    # 2. Create a FeatureGroup to hold ALL the AntPaths
    forbidden_turns_group = folium.FeatureGroup(name="Forbidden Turns", show=True)

    for source_id, row in edges.iterrows():
        forbidden_targets = row["forbidden_turns"]

        if forbidden_targets is not None:
            if isinstance(forbidden_targets, np.ndarray):
                forbidden_targets = forbidden_targets.tolist()
            elif not isinstance(forbidden_targets, list):
                forbidden_targets = [forbidden_targets]

            for target_id in forbidden_targets:
                try:
                    target_row = edges.loc[target_id]

                    source_coords = [(lat, lon) for lon, lat in row["geometry"].coords]
                    target_coords = [
                        (lat, lon) for lon, lat in target_row["geometry"].coords
                    ]

                    turn_path = source_coords + target_coords
                    tooltip_text = f"Forbidden Turn: {source_id} ➔ {target_id}"

                    # Add the AntPath to the FeatureGroup instead of directly to the map
                    AntPath(
                        locations=turn_path,
                        color="red",
                        weight=4,
                        tooltip=tooltip_text,
                        dash_array=[10, 15],
                        delay=800,
                    ).add_to(forbidden_turns_group)

                except AttributeError:
                    logging.warn(
                        f"Geometry not found for source {source_id} or target {target_id}. Skipping this forbidden turn."
                    )
                    pass
                except KeyError:
                    pass

    # Add the whole group to the map
    forbidden_turns_group.add_to(m)

    # 3. Add the layer control (this creates the toggle UI)
    folium.LayerControl(collapsed=False).add_to(m)

    m.save(OUTPUT_DIR / "forbidden_turns.html")
    logging.info(
        f"Map with forbidden turns saved to {OUTPUT_DIR / 'forbidden_turns.html'}"
    )


if __name__ == "__main__":
    OUTPUT_DIR.mkdir(exist_ok=True)
    main()
